### PR TITLE
Typo Fix

### PR DESCRIPTION
**Pull request by sudhanshu-77**
Look for > Looking for
 respository > repository

### CODE REVIEW

**Comment by sudhanshu-77** [comment]
Hi 👋, @ccbogel Please review the changes and merge. Thanks

**Comment by sudhanshu-77** [comment]
@ccbogel ,Please review and merge this fix. I am aiming for Hacktoberfest/ Hacksquad and today is the last day.

**Comment by ccbogel** [comment]
fixed this one, the other change i didnt

**Comment by ccbogel** [comment]
wasting my time. find another repository to fix

**Pull request closed without merging**
